### ISSUE TITLE
lab3 needs more work to run

### ISSUE THREAD

**Issue by afrancoc2000** [microsoft/llmops-workshop#6]
When I tried to run the lab 3 as said in the guide, I encountered an issue with the documents. They came with the vectors and that made it impossible to run in the queries to the LLM.

I had to:

1. Change documents input type to list.
2. Change `validate_input` block adding a validate_list method without the strip string.
3. Change every prompt block that included a `{{FullBody}}` line in the jinga2 file like this:

```python
{% for document in documents %}
{{ document.text }}

{% endfor %}
```

After running these steps, I was finally able to do the evaluation of the results.

**Comment by placerda** [comment]
Hi Ana, thanks for the feedback. I pushed some updates on labs 2 and 3 related to the indexing approach for the RAG part that will solve this issue, let me know in case you face additional issues. #8

**Comment by afrancoc2000** [comment]
Thanks!
